version: "1.0"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rest-api
  auth-db:
    image: postgres:latest
    container_name: auth-db
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    networks:
      - rest-api
    ports:
      - "5433:5432"
  product-db:
    image: postgres:latest
    container_name: product-db
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /data/postgres
    networks:
      - rest-api
    ports:
      - "5433:5433"
  sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    networks:
      - rest-api
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - 27018:27017
networks:
  rest-api:
    driver: bridge